In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.pyplot import figure

In [2]:
df = pd.read_csv('/Users/jjruiz/Downloads/ACSST1Y2018.S2801_2022-01-19T092517/Internet_Subs_by_State_with_County_2018.csv')

In [3]:
print(df.shape)
df.head(20)

(839, 126)

,GEO_ID,NAME,S2801_C01_001E,S2801_C01_001M,S2801_C01_002E,S2801_C01_002M,S2801_C01_003E,S2801_C01_003M,S2801_C01_004E,S2801_C01_004M,...,S2801_C02_027E,S2801_C02_027M,S2801_C02_028E,S2801_C02_028M,S2801_C02_029E,S2801_C02_029M,S2801_C02_030E,S2801_C02_030M,S2801_C02_031E,S2801_C02_031M
0,id,Geographic Area Name,Estimate!!Total!!Total households,Margin of Error!!Total MOE!!Total households,Estimate!!Total!!TYPES OF COMPUTER!!Has one or...,Margin of Error!!Total MOE!!TYPES OF COMPUTER!...,Estimate!!Total!!TYPES OF COMPUTER!!Has one or...,Margin of Error!!Total MOE!!TYPES OF COMPUTER!...,Estimate!!Total!!TYPES OF COMPUTER!!Has one or...,Margin of Error!!Total MOE!!TYPES OF COMPUTER!...,...,Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTI...,Margin of Error!!Percent MOE!!TYPE OF INTERNET...,Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTI...,Margin of Error!!Percent MOE!!TYPE OF INTERNET...,Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTI...,Margin of Error!!Percent MOE!!TYPE OF INTERNET...,Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTI...,Margin of Error!!Percent MOE!!TYPE OF INTERNET...,Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTI...,Margin of Error!!Percent MOE!!TYPE OF INTERNET...
1,0500000US01003,"Baldwin County, Alabama",83501,2931,77443,2976,62729,3103,4403,1110,...,18.2,4.2,(X),(X),0.0,0.5,95.0,2.3,5.0,2.3
2,0500000US01015,"Calhoun County, Alabama",44264,1834,38768,1871,30768,1971,3054,879,...,20.9,4.4,(X),(X),0.2,0.4,87.3,5.6,12.5,5.6
3,0500000US01043,"Cullman County, Alabama",30323,1437,26269,1408,19117,1648,654,324,...,19.4,4.8,(X),(X),0.0,1.9,90.4,4.8,9.6,4.8
4,0500000US01049,"DeKalb County, Alabama",26462,1458,22675,1395,15879,1478,1440,692,...,19.3,4.8,(X),(X),0.0,2.5,94.8,4.1,5.2,4.1
5,0500000US01051,"Elmore County, Alabama",30155,1094,26120,1194,21528,1274,599,356,...,16.8,6.4,(X),(X),0.0,1.4,91.9,4.6,8.1,4.6
6,0500000US01055,"Etowah County, Alabama",38625,1544,34041,1772,23824,1641,1682,569,...,20.8,5.1,(X),(X),0.0,1.4,92.6,3.6,7.4,3.6
7,0500000US01069,"Houston County, Alabama",38861,1098,31815,1167,24932,1068,3843,589,...,23.8,3.7,(X),(X),0.2,0.3,90.3,2.2,9.5,2.3
8,0500000US01073,"Jefferson County, Alabama",255940,3851,228104,4302,182830,4522,7648,1218,...,16.5,1.8,(X),(X),0.0,0.1,94.4,1.4,5.6,1.4
9,0500000US01077,"Lauderdale County, Alabama",38670,1735,33173,2072,26145,2001,2465,823,...,25.5,5.2,(X),(X),0.0,1.4,88.6,5.5,11.4,5.5
10,0500000US01081,"Lee County, Alabama",59336,1847,54953,2202,46742,2701,1720,697,...,18.9,5.3,(X),(X),0.0,0.8,95.6,2.8,4.4,2.8
11,0500000US01083,"Limestone County, Alabama",32333,1294,29448,1423,24010,1615,997,399,...,16.8,5.7,(X),(X),0.0,1.2,93.2,4.5,6.8,4.5
12,0500000US01089,"Madison County, Alabama",152723,1873,142330,2671,123026,3935,5721,1052,...,13.0,2.8,(X),(X),0.0,0.3,95.9,1.7,4.1,1.7
13,0500000US01095,"Marshall County, Alabama",36022,1112,31983,1408,23158,1900,1282,430,...,13.3,3.9,(X),(X),0.0,1.5,92.7,4.9,7.3,4.9
14,0500000US01097,"Mobile County, Alabama",158627,3164,139806,3179,98921,3209,5796,1130,...,18.5,2.2,(X),(X),3.5,2.5,91.2,2.6,5.3,1.9
15,0500000US01101,"Montgomery County, Alabama",87553,2304,77480,2684,57320,2757,2629,688,...,13.3,2.9,(X),(X),0.3,0.5,94.4,2.0,5.3,2.0
16,0500000US01103,"Morgan County, Alabama",45851,1482,39562,1910,33452,2013,2728,954,...,23.0,5.3,(X),(X),0.0,1.0,94.2,3.9,5.8,3.9
17,0500000US01115,"St. Clair County, Alabama",30765,1596,27064,1950,22292,1965,2325,1050,...,17.1,6.7,(X),(X),0.0,1.6,98.6,1.5,1.4,1.5
18,0500000US01117,"Shelby County, Alabama",80944,1588,77041,1777,65403,2147,1715,578,...,11.9,2.9,(X),(X),0.0,0.4,98.3,1.0,1.7,1.0
19,0500000US01121,"Talladega County, Alabama",31219,1460,26614,1675,20191,1735,1601,548,...,14.0,3.9,(X),(X),0.0,2.1,94.2,3.6,5.8,3.6

In [4]:
E_names = df.copy()
E_names = E_names.iloc[[0]]
E_names.reset_index()
E_names = E_names.drop(columns = E_names.columns.astype(str)[E_names.columns.str.contains("M")], axis =1, inplace = False)
E_names.columns = E_names.iloc[0]
E_names = E_names.iloc[1:].reset_index(drop=True)
pd.options.display.max_columns = 100
list(E_names)

['id',
 'Estimate!!Total!!Total households',
 'Estimate!!Total!!TYPES OF COMPUTER!!Has one or more types of computing devices',
 'Estimate!!Total!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Desktop or laptop',
 'Estimate!!Total!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Desktop or laptop!!Desktop or laptop with no other type of computing device',
 'Estimate!!Total!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Smartphone',
 'Estimate!!Total!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Smartphone!!Smartphone with no other type of computing device',
 'Estimate!!Total!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Tablet or other portable wireless computer',
 'Estimate!!Total!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Tablet or other portable wireless computer!!Tablet or other portable wireless computer with no other type of computing device',
 'Estimate!!Total!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Other computer',
 'Estimate!!Total!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Other computer!!Other computer with no other type of computing device',
 'Estimate!!Total!!TYPES OF COMPUTER!!No computer',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription!!Dial-up with no other type of Internet subscription',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription!!Broadband of any type',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription!!Broadband of any type!!Cellular data plan',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription!!Broadband of any type!!Cellular data plan!!Cellular data plan with no other type of Internet subscription',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription!!Broadband of any type!!Broadband such as cable, fiber optic or DSL',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription!!Broadband of any type!!Satellite Internet service',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!Without an Internet subscription',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!Less than $20,000',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!Less than $20,000!!With dial-up Internet subscription alone',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!Less than $20,000!!With a broadband Internet subscription',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!Less than $20,000!!Without an Internet subscription',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!$20,000 to $74,999',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!$20,000 to $74,999!!With dial-up Internet subscription alone',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!$20,000 to $74,999!!With a broadband Internet subscription',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!$20,000 to $74,999!!Without an Internet subscription',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!$75,000 or more',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!$75,000 or more!!With dial-up Internet subscription alone',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!$75,000 or more!!With a broadband Internet subscription',
 'Estimate!!Total!!TYPE OF INTERNET SUBSCRIPTIONS!!$75,000 or more!!Without an Internet subscription',
 'Estimate!!Percent!!Total households',
 'Estimate!!Percent!!TYPES OF COMPUTER!!Has one or more types of computing devices',
 'Estimate!!Percent!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Desktop or laptop',
 'Estimate!!Percent!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Desktop or laptop!!Desktop or laptop with no other type of computing device',
 'Estimate!!Percent!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Smartphone',
 'Estimate!!Percent!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Smartphone!!Smartphone with no other type of computing device',
 'Estimate!!Percent!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Tablet or other portable wireless computer',
 'Estimate!!Percent!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Tablet or other portable wireless computer!!Tablet or other portable wireless computer with no other type of computing device',
 'Estimate!!Percent!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Other computer',
 'Estimate!!Percent!!TYPES OF COMPUTER!!Has one or more types of computing devices!!Other computer!!Other computer with no other type of computing device',
 'Estimate!!Percent!!TYPES OF COMPUTER!!No computer',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription!!Dial-up with no other type of Internet subscription',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription!!Broadband of any type',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription!!Broadband of any type!!Cellular data plan',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription!!Broadband of any type!!Cellular data plan!!Cellular data plan with no other type of Internet subscription',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription!!Broadband of any type!!Broadband such as cable, fiber optic or DSL',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!With an Internet subscription!!Broadband of any type!!Satellite Internet service',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!Without an Internet subscription',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!Less than $20,000',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!Less than $20,000!!With dial-up Internet subscription alone',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!Less than $20,000!!With a broadband Internet subscription',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!Less than $20,000!!Without an Internet subscription',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!$20,000 to $74,999',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!$20,000 to $74,999!!With dial-up Internet subscription alone',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!$20,000 to $74,999!!With a broadband Internet subscription',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!$20,000 to $74,999!!Without an Internet subscription',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!$75,000 or more',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!$75,000 or more!!With dial-up Internet subscription alone',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!$75,000 or more!!With a broadband Internet subscription',
 'Estimate!!Percent!!TYPE OF INTERNET SUBSCRIPTIONS!!$75,000 or more!!Without an Internet subscription']

In [5]:
Subs_formatted = df
Subs_formatted = Subs_formatted.iloc[1: , :]
Subs_formatted[['county', 'state']] = Subs_formatted['NAME'].str.split(',', expand=True)
Subs_formatted = Subs_formatted.drop('NAME', 1)
Subs_formatted.head()

/Applications/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

,GEO_ID,S2801_C01_001E,S2801_C01_001M,S2801_C01_002E,S2801_C01_002M,S2801_C01_003E,S2801_C01_003M,S2801_C01_004E,S2801_C01_004M,S2801_C01_005E,S2801_C01_005M,S2801_C01_006E,S2801_C01_006M,S2801_C01_007E,S2801_C01_007M,S2801_C01_008E,S2801_C01_008M,S2801_C01_009E,S2801_C01_009M,S2801_C01_010E,S2801_C01_010M,S2801_C01_011E,S2801_C01_011M,S2801_C01_012E,S2801_C01_012M,S2801_C01_013E,S2801_C01_013M,S2801_C01_014E,S2801_C01_014M,S2801_C01_015E,S2801_C01_015M,S2801_C01_016E,S2801_C01_016M,S2801_C01_017E,S2801_C01_017M,S2801_C01_018E,S2801_C01_018M,S2801_C01_019E,S2801_C01_019M,S2801_C01_020E,S2801_C01_020M,S2801_C01_021E,S2801_C01_021M,S2801_C01_022E,S2801_C01_022M,S2801_C01_023E,S2801_C01_023M,S2801_C01_024E,S2801_C01_024M,S2801_C01_025E,...,S2801_C02_008E,S2801_C02_008M,S2801_C02_009E,S2801_C02_009M,S2801_C02_010E,S2801_C02_010M,S2801_C02_011E,S2801_C02_011M,S2801_C02_012E,S2801_C02_012M,S2801_C02_013E,S2801_C02_013M,S2801_C02_014E,S2801_C02_014M,S2801_C02_015E,S2801_C02_015M,S2801_C02_016E,S2801_C02_016M,S2801_C02_017E,S2801_C02_017M,S2801_C02_018E,S2801_C02_018M,S2801_C02_019E,S2801_C02_019M,S2801_C02_020E,S2801_C02_020M,S2801_C02_021E,S2801_C02_021M,S2801_C02_022E,S2801_C02_022M,S2801_C02_023E,S2801_C02_023M,S2801_C02_024E,S2801_C02_024M,S2801_C02_025E,S2801_C02_025M,S2801_C02_026E,S2801_C02_026M,S2801_C02_027E,S2801_C02_027M,S2801_C02_028E,S2801_C02_028M,S2801_C02_029E,S2801_C02_029M,S2801_C02_030E,S2801_C02_030M,S2801_C02_031E,S2801_C02_031M,county,state
1,0500000US01003,83501,2931,77443,2976,62729,3103,4403,1110,70185,3289,9358,1887,53266,3460,1100,747,1184,646,0,201,6058,1474,71067,3036,433,393,70634,2994,65198,3075,16557,2677,48113,2969,10767,1766,12434,2350,10488,1880,162,216,7149,1624,3177,999,42398,2965,271,...,1.3,0.9,1.4,0.8,0.0,0.2,7.3,1.7,85.1,2.7,0.5,0.5,84.6,2.7,78.1,2.9,19.8,3.1,57.6,3.3,12.9,2.1,14.9,2.7,(X),(X),1.5,2.1,68.2,8.5,30.3,8.3,(X),(X),0.6,0.7,81.1,4.2,18.2,4.2,(X),(X),0.0,0.5,95.0,2.3,5.0,2.3,Baldwin County,Alabama
2,0500000US01015,44264,1834,38768,1871,30768,1971,3054,879,32921,2200,3865,911,25422,1914,1164,549,1225,504,82,107,5496,969,34344,1827,229,205,34115,1824,27732,2037,6463,1285,24763,1680,4914,1279,9920,1223,10046,1536,66,112,6094,1104,3886,859,20912,2038,135,...,2.6,1.2,2.8,1.1,0.2,0.2,12.4,2.1,77.6,2.6,0.5,0.5,77.1,2.6,62.7,3.9,14.6,2.8,55.9,3.1,11.1,2.8,22.4,2.6,(X),(X),0.7,1.1,60.7,5.9,38.7,6.0,(X),(X),0.6,0.8,78.4,4.2,20.9,4.4,(X),(X),0.2,0.4,87.3,5.6,12.5,5.6,Calhoun County,Alabama
3,0500000US01043,30323,1437,26269,1408,19117,1648,654,324,24088,1604,3948,961,17024,1257,689,529,447,285,48,79,4054,753,24503,1394,204,216,24299,1389,21512,1502,7213,1173,14954,1365,3016,864,5820,1065,5935,1093,0,201,4020,942,1915,635,15884,1568,204,...,2.3,1.8,1.5,0.9,0.2,0.3,13.4,2.4,80.8,3.2,0.7,0.7,80.1,3.2,70.9,4.0,23.8,3.7,49.3,4.4,9.9,2.7,19.2,3.2,(X),(X),0.0,2.8,67.7,9.2,32.3,9.2,(X),(X),1.3,1.4,79.3,4.6,19.4,4.8,(X),(X),0.0,1.9,90.4,4.8,9.6,4.8,Cullman County,Alabama
4,0500000US01049,26462,1458,22675,1395,15879,1478,1440,692,20442,1482,4172,1000,13094,1451,306,254,250,202,0,201,3787,904,20646,1407,0,201,20646,1407,18541,1510,4939,916,14450,1450,2077,669,5816,1154,6787,1126,0,201,3853,1041,2934,916,13191,1442,0,...,1.2,1.0,0.9,0.8,0.0,0.6,14.3,3.2,78.0,4.0,0.0,0.6,78.0,4.0,70.1,4.9,18.7,3.3,54.6,4.8,7.8,2.5,22.0,4.0,(X),(X),0.0,2.4,56.8,11.9,43.2,11.9,(X),(X),0.0,1.3,80.7,4.8,19.3,4.8,(X),(X),0.0,2.5,94.8,4.1,5.2,4.1,DeKalb County,Alabama
5,0500000US01051,30155,1094,26120,1194,21528,1274,599,356,24958,1336,2809,994,19449,1376,313,281,717,420,0,201,4035,874,24772,1297,41,68,24731,1302,20312,1585,2983,804,20463,1332,2201,695,5383,1158,5082,1096,0,201,2908,781,2174,697,13576,1650,41,...,1.0,0.9,2.4,1.4,0.0,0.6,13.4,2.8,82.1,3.7,0.1,0.2,82.0,3.7,67.4,4.7,9.9,2.6,67.9,4.0,7.3,2.3,17.9,3.7,(X),(X),0.0,3.2,57.2,9.8,42.8,9.8,(X),(X),0.3,0.5,82.9,6.4,16.8,6.4,(X),(X),0.0,1.4,91.9,4.6,8.1,4.6,Elmore County,Alabama

In [6]:
Subs_formatted.columns[Subs_formatted.columns.str.contains("E")]

Index(['GEO_ID', 'S2801_C01_001E', 'S2801_C01_002E', 'S2801_C01_003E',
       'S2801_C01_004E', 'S2801_C01_005E', 'S2801_C01_006E', 'S2801_C01_007E',
       'S2801_C01_008E', 'S2801_C01_009E', 'S2801_C01_010E', 'S2801_C01_011E',
       'S2801_C01_012E', 'S2801_C01_013E', 'S2801_C01_014E', 'S2801_C01_015E',
       'S2801_C01_016E', 'S2801_C01_017E', 'S2801_C01_018E', 'S2801_C01_019E',
       'S2801_C01_020E', 'S2801_C01_021E', 'S2801_C01_022E', 'S2801_C01_023E',
       'S2801_C01_024E', 'S2801_C01_025E', 'S2801_C01_026E', 'S2801_C01_027E',
       'S2801_C01_028E', 'S2801_C01_029E', 'S2801_C01_030E', 'S2801_C01_031E',
       'S2801_C02_001E', 'S2801_C02_002E', 'S2801_C02_003E', 'S2801_C02_004E',
       'S2801_C02_005E', 'S2801_C02_006E', 'S2801_C02_007E', 'S2801_C02_008E',
       'S2801_C02_009E', 'S2801_C02_010E', 'S2801_C02_011E', 'S2801_C02_012E',
       'S2801_C02_013E', 'S2801_C02_014E', 'S2801_C02_015E', 'S2801_C02_016E',
       'S2801_C02_017E', 'S2801_C02_018E', 'S2801_C02_019E', 'S2801_C02_020E',
       'S2801_C02_021E', 'S2801_C02_022E', 'S2801_C02_023E', 'S2801_C02_024E',
       'S2801_C02_025E', 'S2801_C02_026E', 'S2801_C02_027E', 'S2801_C02_028E',
       'S2801_C02_029E', 'S2801_C02_030E', 'S2801_C02_031E'],
      dtype='object')

In [7]:
overall_pop_EST_data_Subs = Subs_formatted[["GEO_ID", "county", "state",'S2801_C01_001E', 'S2801_C01_002E', 'S2801_C01_003E',
       'S2801_C01_004E', 'S2801_C01_005E', 'S2801_C01_006E', 'S2801_C01_007E',
       'S2801_C01_008E', 'S2801_C01_009E', 'S2801_C01_010E', 'S2801_C01_011E',
       'S2801_C01_012E', 'S2801_C01_013E', 'S2801_C01_014E', 'S2801_C01_015E',
       'S2801_C01_016E', 'S2801_C01_017E', 'S2801_C01_018E', 'S2801_C01_019E',
       'S2801_C01_020E', 'S2801_C01_021E', 'S2801_C01_022E', 'S2801_C01_023E',
       'S2801_C01_024E', 'S2801_C01_025E', 'S2801_C01_026E', 'S2801_C01_027E',
       'S2801_C01_028E', 'S2801_C01_029E', 'S2801_C01_030E', 'S2801_C01_031E',
       'S2801_C02_001E', 'S2801_C02_002E', 'S2801_C02_003E', 'S2801_C02_004E',
       'S2801_C02_005E', 'S2801_C02_006E', 'S2801_C02_007E', 'S2801_C02_008E',
       'S2801_C02_009E', 'S2801_C02_010E', 'S2801_C02_011E', 'S2801_C02_012E',
       'S2801_C02_013E', 'S2801_C02_014E', 'S2801_C02_015E', 'S2801_C02_016E',
       'S2801_C02_017E', 'S2801_C02_018E', 'S2801_C02_019E', 'S2801_C02_020E',
       'S2801_C02_021E', 'S2801_C02_022E', 'S2801_C02_023E', 'S2801_C02_024E',
       'S2801_C02_025E', 'S2801_C02_026E', 'S2801_C02_027E', 'S2801_C02_028E',
       'S2801_C02_029E', 'S2801_C02_030E', 'S2801_C02_031E']]
overall_pop_EST_data_Subs.head(10)

,GEO_ID,county,state,S2801_C01_001E,S2801_C01_002E,S2801_C01_003E,S2801_C01_004E,S2801_C01_005E,S2801_C01_006E,S2801_C01_007E,S2801_C01_008E,S2801_C01_009E,S2801_C01_010E,S2801_C01_011E,S2801_C01_012E,S2801_C01_013E,S2801_C01_014E,S2801_C01_015E,S2801_C01_016E,S2801_C01_017E,S2801_C01_018E,S2801_C01_019E,S2801_C01_020E,S2801_C01_021E,S2801_C01_022E,S2801_C01_023E,S2801_C01_024E,S2801_C01_025E,S2801_C01_026E,S2801_C01_027E,S2801_C01_028E,S2801_C01_029E,S2801_C01_030E,S2801_C01_031E,S2801_C02_001E,S2801_C02_002E,S2801_C02_003E,S2801_C02_004E,S2801_C02_005E,S2801_C02_006E,S2801_C02_007E,S2801_C02_008E,S2801_C02_009E,S2801_C02_010E,S2801_C02_011E,S2801_C02_012E,S2801_C02_013E,S2801_C02_014E,S2801_C02_015E,S2801_C02_016E,S2801_C02_017E,S2801_C02_018E,S2801_C02_019E,S2801_C02_020E,S2801_C02_021E,S2801_C02_022E,S2801_C02_023E,S2801_C02_024E,S2801_C02_025E,S2801_C02_026E,S2801_C02_027E,S2801_C02_028E,S2801_C02_029E,S2801_C02_030E,S2801_C02_031E
1,0500000US01003,Baldwin County,Alabama,83501,77443,62729,4403,70185,9358,53266,1100,1184,0,6058,71067,433,70634,65198,16557,48113,10767,12434,10488,162,7149,3177,42398,271,34396,7731,30615,0,29089,1526,(X),92.7,75.1,5.3,84.1,11.2,63.8,1.3,1.4,0.0,7.3,85.1,0.5,84.6,78.1,19.8,57.6,12.9,14.9,(X),1.5,68.2,30.3,(X),0.6,81.1,18.2,(X),0.0,95.0,5.0
2,0500000US01015,Calhoun County,Alabama,44264,38768,30768,3054,32921,3865,25422,1164,1225,82,5496,34344,229,34115,27732,6463,24763,4914,9920,10046,66,6094,3886,20912,135,16402,4375,13306,28,11619,1659,(X),87.6,69.5,6.9,74.4,8.7,57.4,2.6,2.8,0.2,12.4,77.6,0.5,77.1,62.7,14.6,55.9,11.1,22.4,(X),0.7,60.7,38.7,(X),0.6,78.4,20.9,(X),0.2,87.3,12.5
3,0500000US01043,Cullman County,Alabama,30323,26269,19117,654,24088,3948,17024,689,447,48,4054,24503,204,24299,21512,7213,14954,3016,5820,5935,0,4020,1915,15884,204,12595,3085,8504,0,7684,820,(X),86.6,63.0,2.2,79.4,13.0,56.1,2.3,1.5,0.2,13.4,80.8,0.7,80.1,70.9,23.8,49.3,9.9,19.2,(X),0.0,67.7,32.3,(X),1.3,79.3,19.4,(X),0.0,90.4,9.6
4,0500000US01049,DeKalb County,Alabama,26462,22675,15879,1440,20442,4172,13094,306,250,0,3787,20646,0,20646,18541,4939,14450,2077,5816,6787,0,3853,2934,13191,0,10649,2542,6484,0,6144,340,(X),85.7,60.0,5.4,77.3,15.8,49.5,1.2,0.9,0.0,14.3,78.0,0.0,78.0,70.1,18.7,54.6,7.8,22.0,(X),0.0,56.8,43.2,(X),0.0,80.7,19.3,(X),0.0,94.8,5.2
5,0500000US01051,Elmore County,Alabama,30155,26120,21528,599,24958,2809,19449,313,717,0,4035,24772,41,24731,20312,2983,20463,2201,5383,5082,0,2908,2174,13576,41,11261,2274,11497,0,10562,935,(X),86.6,71.4,2.0,82.8,9.3,64.5,1.0,2.4,0.0,13.4,82.1,0.1,82.0,67.4,9.9,67.9,7.3,17.9,(X),0.0,57.2,42.8,(X),0.3,82.9,16.8,(X),0.0,91.9,8.1
6,0500000US01055,Etowah County,Alabama,38625,34041,23824,1682,30802,6626,18929,403,673,171,4584,31585,0,31585,28133,7585,22062,2845,7040,6727,0,4704,2023,19791,0,15667,4124,12107,0,11214,893,(X),88.1,61.7,4.4,79.7,17.2,49.0,1.0,1.7,0.4,11.9,81.8,0.0,81.8,72.8,19.6,57.1,7.4,18.2,(X),0.0,69.9,30.1,(X),0.0,79.2,20.8,(X),0.0,92.6,7.4
7,0500000US01069,Houston County,Alabama,38861,31815,24932,3843,27072,4870,18327,344,720,22,7046,29012,192,28820,24742,5333,22427,1990,9849,8553,48,4122,4383,18022,121,13603,4298,12286,23,11095,1168,(X),81.9,64.2,9.9,69.7,12.5,47.2,0.9,1.9,0.1,18.1,74.7,0.5,74.2,63.7,13.7,57.7,5.1,25.3,(X),0.6,48.2,51.2,(X),0.7,75.5,23.8,(X),0.2,90.3,9.5
8,0500000US01073,Jefferson County,Alabama,255940,228104,182830,7648,211652,27675,148073,2633,4549,0,27836,213733,163,213570,194809,38354,166462,19775,42207,47935,0,29604,18331,112253,122,93574,18557,95752,41,90392,5319,(X),89.1,71.4,3.0,82.7,10.8,57.9,1.0,1.8,0.0,10.9,83.5,0.1,83.4,76.1,15.0,65.0,7.7,16.5,(X),0.0,61.8,38.2,(X),0.1,83.4,16.5,(X),0.0,94.4,5.6
9,0500000US01077,Lauderdale County,Alabama,38670,33173,26145,2465,29423,4884,19788,594,946,0,5497,29439,50,29389,26258,7878,19290,3458,9231,7132,0,4289,2843,19801,50,14701,5050,11737,0,10399,1338,(X),85.8,67.6,6.4,76.1,12.6,51.2,1.5,2.4,0.0,14.2,76.1,0.1,76.0,67.9,20.4,49.9,8.9,23.9,(X),0.0,60.1,39.9,(X),0.3,74.2,25.5,(X),0.0,88.6,11.4
10,0500000US01081,Lee County,Alabama,59336,54953,46742,1720,52100,3724,40170,457,1500,0,4383,48633,237,48396,44473,5951,39702,8367,10703,14817,0,9465,5352,23460,237,18799,4424,21059,0,20132,927,(X),92.6,78.8,2.9,87.8,6.3,67.7,0.8,2.5,0.0,7.4,82.0,0.4,81.6,75.0,10.0,66.9,14.1,18.0,(X),0.0,63.9,36.1,(X),1.0,80.1,18.9,(X),0.0,95.6,4.4

In [8]:
overall_pop_EST_dict = {
                "S2801_C01_001E":"est_total_households", 
                "S2801_C01_002E":"est_total_households_with_Device", 
                "S2801_C01_003E":"est_total_households_with_Desktop", 
                "S2801_C01_004E":"est_total_households_with_NO",
                "S2801_C01_005E":"est_total_households_with_Smartphone",
                "S2801_C01_006E":"est_total_households_with_NO2",
                "S2801_C01_007E":"est_total_households_with_Portable", 
                "S2801_C01_008E":"est_total_households_with_NO3", 
                "S2801_C01_009E":"est_total_households_with_Other",
                "S2801_C01_010E":"est_total_households_with_NO4", 
                "S2801_C01_011E":"est_total_households_No_Device", 
                "S2801_C01_012E":"est_total_households_with_SUB", 
                'S2801_C01_013E':"est_total_households_with_DU",
                'S2801_C01_014E': "est_total_households_with_Broadband",
                'S2801_C01_015E':"est_total_households_with_Cellular",
                'S2801_C01_016E':"est_total_households_with_Cell_NO",
                'S2801_C01_017E':"est_total_households_with_Cable",
                'S2801_C01_018E':"est_total_households_with_SAT",
                'S2801_C01_019E':"est_total_households_without_SUB",
                'S2801_C01_020E':"est_total_20k_households",
                'S2801_C01_021E':"est_total_20k_households_with_DU",
                'S2801_C01_022E':"est_total_20k_households_with_Broadband",
                'S2801_C01_023E':"est_total_20k_households_without_SUB",
                'S2801_C01_024E':"est_total_under75k_households",
                'S2801_C01_025E':"est_total_under75k_households_with_DU",
                'S2801_C01_026E':"est_total_under75k_households_with_BB",
                'S2801_C01_027E':"est_total_under75k_households_without_SUB",
                'S2801_C01_028E':"est_total_75k_households",
                'S2801_C01_029E':"est_total_75k_households_with_DU",
                'S2801_C01_030E':"est_total_75k_households_with_BB",
                'S2801_C01_031E':"est_total_75k_households_without_SUB",
                "S2801_C02_001E":"PCT_total_households", 
                "S2801_C02_002E":"PCT_total_households_with_Device", 
                "S2801_C02_003E":"PCT_total_households_with_Desktop", 
                "S2801_C02_004E":"PCT_total_households_with_NO",
                "S2801_C02_005E":"PCT_total_households_with_Smartphone",
                "S2801_C02_006E":"PCT_total_households_with_NO2",
                "S2801_C02_007E":"PCT_total_households_with_Portable", 
                "S2801_C02_008E":"PCT_total_households_with_NO3", 
                "S2801_C02_009E":"PCT_total_households_with_Other",
                "S2801_C02_010E":"PCT_total_households_with_NO4", 
                "S2801_C02_011E":"PCT_total_households_No_Device", 
                "S2801_C02_012E":"PCT_total_households_with_SUB", 
                'S2801_C02_013E':"PCT_total_households_with_DU",
                'S2801_C02_014E':"PCT_total_households_with_Broadband",
                'S2801_C02_015E':"PCT_total_households_with_Cellular",
                'S2801_C02_016E':"PCT_total_households_with_Cell_NO",
                'S2801_C02_017E':"PCT_total_households_with_Cable",
                'S2801_C02_018E':"PCT_total_households_with_SAT",
                'S2801_C02_019E':"PCT_total_households_without_SUB",
                'S2801_C02_020E':"PCT_total_20k_households",
                'S2801_C02_021E':"PCT_total_20k_households_with_DU",
                'S2801_C02_022E':"PCT_total_20k_households_with_Broadband",
                'S2801_C02_023E':"PCT_total_20k_households_without_SUB",
                'S2801_C02_024E':"PCT_total_under75k_households",
                'S2801_C02_025E':"PCT_total_under75k_households_with_DU",
                'S2801_C02_026E':"PCT_total_under75k_households_with_BB",
                'S2801_C02_027E':"PCT_total_under75k_households_without_SUB",
                'S2801_C02_028E':"PCT_total_75k_households",
                'S2801_C02_029E':"PCT_total_75k_households_with_DU",
                'S2801_C02_030E':"PCT_total_75k_households_with_BB",
                'S2801_C02_031E':"PCT_total_75k_households_without_SUB",
                          }

overall_pop_EST_data_Subs.rename(columns=overall_pop_EST_dict, inplace=True)
overall_pop_EST_data_Subs

/Applications/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4223: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)

,GEO_ID,county,state,est_total_households,est_total_households_with_Device,est_total_households_with_Desktop,est_total_households_with_NO,est_total_households_with_Smartphone,est_total_households_with_NO2,est_total_households_with_Portable,est_total_households_with_NO3,est_total_households_with_Other,est_total_households_with_NO4,est_total_households_No_Device,est_total_households_with_SUB,est_total_households_with_DU,est_total_households_with_Broadband,est_total_households_with_Cellular,est_total_households_with_Cell_NO,est_total_households_with_Cable,est_total_households_with_SAT,est_total_households_without_SUB,est_total_20k_households,est_total_20k_households_with_DU,est_total_20k_households_with_Broadband,est_total_20k_households_without_SUB,est_total_under75k_households,est_total_under75k_households_with_DU,est_total_under75k_households_with_BB,est_total_under75k_households_without_SUB,est_total_75k_households,est_total_75k_households_with_DU,est_total_75k_households_with_BB,est_total_75k_households_without_SUB,PCT_total_households,PCT_total_households_with_Device,PCT_total_households_with_Desktop,PCT_total_households_with_NO,PCT_total_households_with_Smartphone,PCT_total_households_with_NO2,PCT_total_households_with_Portable,PCT_total_households_with_NO3,PCT_total_households_with_Other,PCT_total_households_with_NO4,PCT_total_households_No_Device,PCT_total_households_with_SUB,PCT_total_households_with_DU,PCT_total_households_with_Broadband,PCT_total_households_with_Cellular,PCT_total_households_with_Cell_NO,PCT_total_households_with_Cable,PCT_total_households_with_SAT,PCT_total_households_without_SUB,PCT_total_20k_households,PCT_total_20k_households_with_DU,PCT_total_20k_households_with_Broadband,PCT_total_20k_households_without_SUB,PCT_total_under75k_households,PCT_total_under75k_households_with_DU,PCT_total_under75k_households_with_BB,PCT_total_under75k_households_without_SUB,PCT_total_75k_households,PCT_total_75k_households_with_DU,PCT_total_75k_households_with_BB,PCT_total_75k_households_without_SUB
1,0500000US01003,Baldwin County,Alabama,83501,77443,62729,4403,70185,9358,53266,1100,1184,0,6058,71067,433,70634,65198,16557,48113,10767,12434,10488,162,7149,3177,42398,271,34396,7731,30615,0,29089,1526,(X),92.7,75.1,5.3,84.1,11.2,63.8,1.3,1.4,0.0,7.3,85.1,0.5,84.6,78.1,19.8,57.6,12.9,14.9,(X),1.5,68.2,30.3,(X),0.6,81.1,18.2,(X),0.0,95.0,5.0
2,0500000US01015,Calhoun County,Alabama,44264,38768,30768,3054,32921,3865,25422,1164,1225,82,5496,34344,229,34115,27732,6463,24763,4914,9920,10046,66,6094,3886,20912,135,16402,4375,13306,28,11619,1659,(X),87.6,69.5,6.9,74.4,8.7,57.4,2.6,2.8,0.2,12.4,77.6,0.5,77.1,62.7,14.6,55.9,11.1,22.4,(X),0.7,60.7,38.7,(X),0.6,78.4,20.9,(X),0.2,87.3,12.5
3,0500000US01043,Cullman County,Alabama,30323,26269,19117,654,24088,3948,17024,689,447,48,4054,24503,204,24299,21512,7213,14954,3016,5820,5935,0,4020,1915,15884,204,12595,3085,8504,0,7684,820,(X),86.6,63.0,2.2,79.4,13.0,56.1,2.3,1.5,0.2,13.4,80.8,0.7,80.1,70.9,23.8,49.3,9.9,19.2,(X),0.0,67.7,32.3,(X),1.3,79.3,19.4,(X),0.0,90.4,9.6
4,0500000US01049,DeKalb County,Alabama,26462,22675,15879,1440,20442,4172,13094,306,250,0,3787,20646,0,20646,18541,4939,14450,2077,5816,6787,0,3853,2934,13191,0,10649,2542,6484,0,6144,340,(X),85.7,60.0,5.4,77.3,15.8,49.5,1.2,0.9,0.0,14.3,78.0,0.0,78.0,70.1,18.7,54.6,7.8,22.0,(X),0.0,56.8,43.2,(X),0.0,80.7,19.3,(X),0.0,94.8,5.2
5,0500000US01051,Elmore County,Alabama,30155,26120,21528,599,24958,2809,19449,313,717,0,4035,24772,41,24731,20312,2983,20463,2201,5383,5082,0,2908,2174,13576,41,11261,2274,11497,0,10562,935,(X),86.6,71.4,2.0,82.8,9.3,64.5,1.0,2.4,0.0,13.4,82.1,0.1,82.0,67.4,9.9,67.9,7.3,17.9,(X),0.0,57.2,42.8,(X),0.3,82.9,16.8,(X),0.0,91.9,8.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,0500000US72113,Ponce Municipio,Puerto Rico,53450,36068,25939,4203,30774,7922,11988,593,625,0,17382,36529,191,36338,34157,15015,20228,1470,16921,28836,191,16894,11751,21005,0,16169,4836,3609,0,3275,334,(X),67.5,48.5,7.9,57.6,14.8,22.4,1.1,1.2,0.0,32.5,68.3,0.4,68.0,63.9,28.1,37.8,2.8,31.7,(X),0.7,58.6,40.8,(X),0.0,77.0,23.0,(X),0.0,90.7,9.3
835,0500000US72127,San Juan Municipio,Puerto Rico,147267,91339,61138,6683,81283,21953,43668,1191,4211,0,55928,78990,2387,76603,67616,26303,45948,4493,68277,67909,432,21760,45717,59117,1533,36499,21085,20241,422,18344,1475,(X),62.0,41.5,4.5,55.2,14.9,29.7,0.8,2.9,0.0,38.0,53.6,1.6,52.0,45.9,17.9,31.2,3.1,46.4,(X),0.6,32.0,67.3,(X),2.6,61.7,35.7,(X),2.1,90.6,7.3
836,0500000US72135,Toa Alta Municipio,Puerto Rico,21511,18109,9721,380,17579,7816,5182,39,0,0,3402,7870,101,7769,7547,3512,3797,453,13641,8874,45,1904,6925,10259,56,4051,6152,2378,0,1814,564,(X),84.2,45.2,1.8,81.7,36.3,24.1,0.2,0.0,0.0,15.8,36.6,0.5,36.1,35.1,16.3,17.7,2.1,63.4,(X),0.5,21.5,78.0,(X),0.5,39.5,60.0,(X),0.0,76.3,23.7
837,0500000US72137,Toa Baja Municipio,Puerto Rico,26085,22944,12758,383,22146,9052,8807,105,158,0,3141,11513,103,11410,8044,3059,7901,748,14572,10299,0,2724,7575,13266,26,6804,6436,2520,77,1882,561,(X),88.0,48.9,1.5,84.9,34.7,33.8,0.4,0.6,0.0,12.0,44.1,0.4,43.7,30.8,11.7,30.3,2.9,55.9,(X),0.0,26.4,73.6,(X),0.2,51.3,48.5,(X),3.1,74.7,22.3
838,0500000US72139,Trujillo Alto Municipio,Puerto Rico,23195,19110,12273,581,18130,5473,9619,185,74,0,4085,18113,43,18070,17322,7453,10158,456,5082,7917,0,4729,3188,11814,43,9947,1824,3464,0,3394,70,(X),82.4,52.9,2.5,78.2,23.6,41.5,0.8,0.3,0.0,17.6,78.1,0.2,77.9,74.7,32.1,43.8,2.0,21.9,(X),0.0,59.7,40.3,(X),0.4,84.2,15.4,(X),0.0,98.0,2.0

In [9]:
EST_df = overall_pop_EST_data_Subs.copy()
EST_df = EST_df.drop(columns = EST_df.columns.astype(str)[EST_df.columns.str.contains("PCT")], axis =1, inplace = False)
EST_df = EST_df.set_index('GEO_ID')
EST_df

,county,state,est_total_households,est_total_households_with_Device,est_total_households_with_Desktop,est_total_households_with_NO,est_total_households_with_Smartphone,est_total_households_with_NO2,est_total_households_with_Portable,est_total_households_with_NO3,est_total_households_with_Other,est_total_households_with_NO4,est_total_households_No_Device,est_total_households_with_SUB,est_total_households_with_DU,est_total_households_with_Broadband,est_total_households_with_Cellular,est_total_households_with_Cell_NO,est_total_households_with_Cable,est_total_households_with_SAT,est_total_households_without_SUB,est_total_20k_households,est_total_20k_households_with_DU,est_total_20k_households_with_Broadband,est_total_20k_households_without_SUB,est_total_under75k_households,est_total_under75k_households_with_DU,est_total_under75k_households_with_BB,est_total_under75k_households_without_SUB,est_total_75k_households,est_total_75k_households_with_DU,est_total_75k_households_with_BB,est_total_75k_households_without_SUB
GEO_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0500000US01003,Baldwin County,Alabama,83501,77443,62729,4403,70185,9358,53266,1100,1184,0,6058,71067,433,70634,65198,16557,48113,10767,12434,10488,162,7149,3177,42398,271,34396,7731,30615,0,29089,1526
0500000US01015,Calhoun County,Alabama,44264,38768,30768,3054,32921,3865,25422,1164,1225,82,5496,34344,229,34115,27732,6463,24763,4914,9920,10046,66,6094,3886,20912,135,16402,4375,13306,28,11619,1659
0500000US01043,Cullman County,Alabama,30323,26269,19117,654,24088,3948,17024,689,447,48,4054,24503,204,24299,21512,7213,14954,3016,5820,5935,0,4020,1915,15884,204,12595,3085,8504,0,7684,820
0500000US01049,DeKalb County,Alabama,26462,22675,15879,1440,20442,4172,13094,306,250,0,3787,20646,0,20646,18541,4939,14450,2077,5816,6787,0,3853,2934,13191,0,10649,2542,6484,0,6144,340
0500000US01051,Elmore County,Alabama,30155,26120,21528,599,24958,2809,19449,313,717,0,4035,24772,41,24731,20312,2983,20463,2201,5383,5082,0,2908,2174,13576,41,11261,2274,11497,0,10562,935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0500000US72113,Ponce Municipio,Puerto Rico,53450,36068,25939,4203,30774,7922,11988,593,625,0,17382,36529,191,36338,34157,15015,20228,1470,16921,28836,191,16894,11751,21005,0,16169,4836,3609,0,3275,334
0500000US72127,San Juan Municipio,Puerto Rico,147267,91339,61138,6683,81283,21953,43668,1191,4211,0,55928,78990,2387,76603,67616,26303,45948,4493,68277,67909,432,21760,45717,59117,1533,36499,21085,20241,422,18344,1475
0500000US72135,Toa Alta Municipio,Puerto Rico,21511,18109,9721,380,17579,7816,5182,39,0,0,3402,7870,101,7769,7547,3512,3797,453,13641,8874,45,1904,6925,10259,56,4051,6152,2378,0,1814,564
0500000US72137,Toa Baja Municipio,Puerto Rico,26085,22944,12758,383,22146,9052,8807,105,158,0,3141,11513,103,11410,8044,3059,7901,748,14572,10299,0,2724,7575,13266,26,6804,6436,2520,77,1882,561
0500000US72139,Trujillo Alto Municipio,Puerto Rico,23195,19110,12273,581,18130,5473,9619,185,74,0,4085,18113,43,18070,17322,7453,10158,456,5082,7917,0,4729,3188,11814,43,9947,1824,3464,0,3394,70

In [10]:
Location_df = EST_df.iloc[:, [0,1]].copy()
Location_df

                                 county         state
GEO_ID
0500000US01003           Baldwin County       Alabama
0500000US01015           Calhoun County       Alabama
0500000US01043           Cullman County       Alabama
0500000US01049            DeKalb County       Alabama
0500000US01051            Elmore County       Alabama
...                                 ...           ...
0500000US72113          Ponce Municipio   Puerto Rico
0500000US72127       San Juan Municipio   Puerto Rico
0500000US72135       Toa Alta Municipio   Puerto Rico
0500000US72137       Toa Baja Municipio   Puerto Rico
0500000US72139  Trujillo Alto Municipio   Puerto Rico

[838 rows x 2 columns]

In [11]:
Device_EST_df = EST_df.iloc[:, [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]].copy()
Device_EST_df

,est_total_households,est_total_households_with_Device,est_total_households_with_Desktop,est_total_households_with_NO,est_total_households_with_Smartphone,est_total_households_with_NO2,est_total_households_with_Portable,est_total_households_with_NO3,est_total_households_with_Other,est_total_households_with_NO4,est_total_households_No_Device,est_total_households_with_SUB,est_total_households_with_DU,est_total_households_with_Broadband,est_total_households_with_Cellular,est_total_households_with_Cell_NO,est_total_households_with_Cable,est_total_households_with_SAT,est_total_households_without_SUB
GEO_ID,,,,,,,,,,,,,,,,,,,
0500000US01003,83501,77443,62729,4403,70185,9358,53266,1100,1184,0,6058,71067,433,70634,65198,16557,48113,10767,12434
0500000US01015,44264,38768,30768,3054,32921,3865,25422,1164,1225,82,5496,34344,229,34115,27732,6463,24763,4914,9920
0500000US01043,30323,26269,19117,654,24088,3948,17024,689,447,48,4054,24503,204,24299,21512,7213,14954,3016,5820
0500000US01049,26462,22675,15879,1440,20442,4172,13094,306,250,0,3787,20646,0,20646,18541,4939,14450,2077,5816
0500000US01051,30155,26120,21528,599,24958,2809,19449,313,717,0,4035,24772,41,24731,20312,2983,20463,2201,5383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0500000US72113,53450,36068,25939,4203,30774,7922,11988,593,625,0,17382,36529,191,36338,34157,15015,20228,1470,16921
0500000US72127,147267,91339,61138,6683,81283,21953,43668,1191,4211,0,55928,78990,2387,76603,67616,26303,45948,4493,68277
0500000US72135,21511,18109,9721,380,17579,7816,5182,39,0,0,3402,7870,101,7769,7547,3512,3797,453,13641
0500000US72137,26085,22944,12758,383,22146,9052,8807,105,158,0,3141,11513,103,11410,8044,3059,7901,748,14572
0500000US72139,23195,19110,12273,581,18130,5473,9619,185,74,0,4085,18113,43,18070,17322,7453,10158,456,5082

In [28]:
Device_EST_df = Device_EST_df.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]].astype('int32')
Device_EST_df.dtypes

est_total_households                    int32
est_total_households_with_Device        int32
est_total_households_with_Desktop       int32
est_total_households_with_NO            int32
est_total_households_with_Smartphone    int32
est_total_households_with_NO2           int32
est_total_households_with_Portable      int32
est_total_households_with_NO3           int32
est_total_households_with_Other         int32
est_total_households_with_NO4           int32
est_total_households_No_Device          int32
est_total_households_with_SUB           int32
est_total_households_with_DU            int32
est_total_households_with_Broadband     int32
est_total_households_with_Cellular      int32
est_total_households_with_Cell_NO       int32
est_total_households_with_Cable         int32
est_total_households_with_SAT           int32
est_total_households_without_SUB        int32
dtype: object

In [29]:
Sub_EST_df = Device_EST_df.iloc[:, [11,12,13,14,15,16,17,18]].copy()
Sub_EST_df

,est_total_households_with_SUB,est_total_households_with_DU,est_total_households_with_Broadband,est_total_households_with_Cellular,est_total_households_with_Cell_NO,est_total_households_with_Cable,est_total_households_with_SAT,est_total_households_without_SUB
GEO_ID,,,,,,,,
0500000US01003,71067,433,70634,65198,16557,48113,10767,12434
0500000US01015,34344,229,34115,27732,6463,24763,4914,9920
0500000US01043,24503,204,24299,21512,7213,14954,3016,5820
0500000US01049,20646,0,20646,18541,4939,14450,2077,5816
0500000US01051,24772,41,24731,20312,2983,20463,2201,5383
...,...,...,...,...,...,...,...,...
0500000US72113,36529,191,36338,34157,15015,20228,1470,16921
0500000US72127,78990,2387,76603,67616,26303,45948,4493,68277
0500000US72135,7870,101,7769,7547,3512,3797,453,13641
0500000US72137,11513,103,11410,8044,3059,7901,748,14572
0500000US72139,18113,43,18070,17322,7453,10158,456,5082

In [33]:
Device_EST_df2 = Device_EST_df.iloc[:, [0,1,2,3,4,5,6,7,8,9,10]].copy()
Device_EST_df2

,est_total_households,est_total_households_with_Device,est_total_households_with_Desktop,est_total_households_with_NO,est_total_households_with_Smartphone,est_total_households_with_NO2,est_total_households_with_Portable,est_total_households_with_NO3,est_total_households_with_Other,est_total_households_with_NO4,est_total_households_No_Device
GEO_ID,,,,,,,,,,,
0500000US01003,83501,77443,62729,4403,70185,9358,53266,1100,1184,0,6058
0500000US01015,44264,38768,30768,3054,32921,3865,25422,1164,1225,82,5496
0500000US01043,30323,26269,19117,654,24088,3948,17024,689,447,48,4054
0500000US01049,26462,22675,15879,1440,20442,4172,13094,306,250,0,3787
0500000US01051,30155,26120,21528,599,24958,2809,19449,313,717,0,4035
...,...,...,...,...,...,...,...,...,...,...,...
0500000US72113,53450,36068,25939,4203,30774,7922,11988,593,625,0,17382
0500000US72127,147267,91339,61138,6683,81283,21953,43668,1191,4211,0,55928
0500000US72135,21511,18109,9721,380,17579,7816,5182,39,0,0,3402
0500000US72137,26085,22944,12758,383,22146,9052,8807,105,158,0,3141
0500000US72139,23195,19110,12273,581,18130,5473,9619,185,74,0,4085

In [14]:
Income_EST_df = EST_df.iloc[:, [21,22,23,24,25,26,27,28,29,30,31,32]].copy()
Income_EST_df

,est_total_20k_households,est_total_20k_households_with_DU,est_total_20k_households_with_Broadband,est_total_20k_households_without_SUB,est_total_under75k_households,est_total_under75k_households_with_DU,est_total_under75k_households_with_BB,est_total_under75k_households_without_SUB,est_total_75k_households,est_total_75k_households_with_DU,est_total_75k_households_with_BB,est_total_75k_households_without_SUB
GEO_ID,,,,,,,,,,,,
0500000US01003,10488,162,7149,3177,42398,271,34396,7731,30615,0,29089,1526
0500000US01015,10046,66,6094,3886,20912,135,16402,4375,13306,28,11619,1659
0500000US01043,5935,0,4020,1915,15884,204,12595,3085,8504,0,7684,820
0500000US01049,6787,0,3853,2934,13191,0,10649,2542,6484,0,6144,340
0500000US01051,5082,0,2908,2174,13576,41,11261,2274,11497,0,10562,935
...,...,...,...,...,...,...,...,...,...,...,...,...
0500000US72113,28836,191,16894,11751,21005,0,16169,4836,3609,0,3275,334
0500000US72127,67909,432,21760,45717,59117,1533,36499,21085,20241,422,18344,1475
0500000US72135,8874,45,1904,6925,10259,56,4051,6152,2378,0,1814,564
0500000US72137,10299,0,2724,7575,13266,26,6804,6436,2520,77,1882,561
0500000US72139,7917,0,4729,3188,11814,43,9947,1824,3464,0,3394,70

In [15]:
Income_EST_df = Income_EST_df.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,11]].replace('N', np.nan)

In [38]:
Income_EST_df = Income_EST_df.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,11]].astype('float')
Income_EST_df.dtypes

est_total_20k_households                     float64
est_total_20k_households_with_DU             float64
est_total_20k_households_with_Broadband      float64
est_total_20k_households_without_SUB         float64
est_total_under75k_households                float64
est_total_under75k_households_with_DU        float64
est_total_under75k_households_with_BB        float64
est_total_under75k_households_without_SUB    float64
est_total_75k_households                     float64
est_total_75k_households_with_DU             float64
est_total_75k_households_with_BB             float64
est_total_75k_households_without_SUB         float64
dtype: object

In [54]:
Total_Income_EST_df = Income_EST_df.iloc[:, [0,4,8]].copy()
Total_Income_EST_df

,est_total_20k_households,est_total_under75k_households,est_total_75k_households
GEO_ID,,,
0500000US01003,10488.0,42398.0,30615.0
0500000US01015,10046.0,20912.0,13306.0
0500000US01043,5935.0,15884.0,8504.0
0500000US01049,6787.0,13191.0,6484.0
0500000US01051,5082.0,13576.0,11497.0
...,...,...,...
0500000US72113,28836.0,21005.0,3609.0
0500000US72127,67909.0,59117.0,20241.0
0500000US72135,8874.0,10259.0,2378.0
0500000US72137,10299.0,13266.0,2520.0
0500000US72139,7917.0,11814.0,3464.0

In [56]:
Subs_by_Income_df = Income_EST_df.drop(columns = ["est_total_20k_households","est_total_under75k_households","est_total_75k_households"]).copy()
Subs_by_Income_df

,est_total_20k_households_with_DU,est_total_20k_households_with_Broadband,est_total_20k_households_without_SUB,est_total_under75k_households_with_DU,est_total_under75k_households_with_BB,est_total_under75k_households_without_SUB,est_total_75k_households_with_DU,est_total_75k_households_with_BB,est_total_75k_households_without_SUB
GEO_ID,,,,,,,,,
0500000US01003,162.0,7149.0,3177.0,271.0,34396.0,7731.0,0.0,29089.0,1526.0
0500000US01015,66.0,6094.0,3886.0,135.0,16402.0,4375.0,28.0,11619.0,1659.0
0500000US01043,0.0,4020.0,1915.0,204.0,12595.0,3085.0,0.0,7684.0,820.0
0500000US01049,0.0,3853.0,2934.0,0.0,10649.0,2542.0,0.0,6144.0,340.0
0500000US01051,0.0,2908.0,2174.0,41.0,11261.0,2274.0,0.0,10562.0,935.0
...,...,...,...,...,...,...,...,...,...
0500000US72113,191.0,16894.0,11751.0,0.0,16169.0,4836.0,0.0,3275.0,334.0
0500000US72127,432.0,21760.0,45717.0,1533.0,36499.0,21085.0,422.0,18344.0,1475.0
0500000US72135,45.0,1904.0,6925.0,56.0,4051.0,6152.0,0.0,1814.0,564.0
0500000US72137,0.0,2724.0,7575.0,26.0,6804.0,6436.0,77.0,1882.0,561.0
0500000US72139,0.0,4729.0,3188.0,43.0,9947.0,1824.0,0.0,3394.0,70.0

PCT_df = overall_pop_EST_data_Subs.copy()
PCT_df = PCT_df.drop(columns = PCT_df.columns.astype(str)[PCT_df.columns.str.contains("est")], axis =1, inplace = False)
PCT_df = PCT_df.set_index('GEO_ID')
PCT_df

Device_PCT_df = PCT_df.iloc[:, [3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]].copy()
Device_PCT_df

Device_PCT_df = Device_EST_df.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]].astype('float')
Device_PCT_df.dtypes

Income_PCT_df = PCT_df.iloc[:, [22,23,24,26,27,28,30,31,32]].copy()
Income_PCT_df

Income_PCT_df = Income_PCT_df.iloc[:, [0,1,2,3,4,5,6,7,8]].replace('N', np.nan)

Income_PCT_df = Income_PCT_df.iloc[:, [0,1,2,3,4,5,6,7,8,]].astype('float')
Income_PCT_df.dtypes

In [34]:
Device_EST_df2.describe().astype('int')

,est_total_households,est_total_households_with_Device,est_total_households_with_Desktop,est_total_households_with_NO,est_total_households_with_Smartphone,est_total_households_with_NO2,est_total_households_with_Portable,est_total_households_with_NO3,est_total_households_with_Other,est_total_households_with_NO4,est_total_households_No_Device
count,838,838,838,838,838,838,838,838,838,838,838
mean,123123,114032,97223,4848,105555,10290,78673,1075,3560,24,9090
std,204640,191328,164531,6675,180544,18690,131426,1430,7303,56,14432
min,20411,11613,7655,308,9774,324,5182,0,0,0,564
25%,36032,32719,26811,1682,29472,3134,21691,354,739,0,3242
50%,59585,55041,46693,2716,49712,4965,37533,630,1452,0,4997
75%,126203,114789,98241,5480,107849,9961,79221,1191,3349,29,9204
max,3313908,3094720,2659755,99419,2933995,282567,2065080,18124,110202,662,219188

In [36]:
Sub_EST_df.describe().astype('int')

,est_total_households_with_SUB,est_total_households_with_DU,est_total_households_with_Broadband,est_total_households_with_Cellular,est_total_households_with_Cell_NO,est_total_households_with_Cable,est_total_households_with_SAT,est_total_households_without_SUB
count,838,838,838,838,838,838,838,838
mean,106526,286,106240,95268,13444,88926,7780,16596
std,178623,433,178266,161981,23014,150890,15429,27698
min,7749,0,7736,6394,1331,3797,453,1295
25%,30228,74,30064,26226,4316,23074,2614,5772
50%,51197,165,51059,44495,6922,41376,4133,8921
75%,110745,339,110455,99212,13465,91160,7614,16362
max,2867792,5933,2861859,2607184,366358,2382268,310982,446116

In [58]:
Subs_by_Income_df.describe()

,est_total_20k_households_with_DU,est_total_20k_households_with_Broadband,est_total_20k_households_without_SUB,est_total_under75k_households_with_DU,est_total_under75k_households_with_BB,est_total_under75k_households_without_SUB,est_total_75k_households_with_DU,est_total_75k_households_with_BB,est_total_75k_households_without_SUB
count,836.000000,836.000000,836.000000,836.000000,8.360000e+02,836.000000,836.000000,8.360000e+02,836.000000
mean,62.565789,11288.556220,6267.078947,165.141148,4.363255e+04,8108.691388,59.315789,5.150563e+04,2257.151914
std,119.965481,19343.360152,11020.158468,239.599874,7.019666e+04,13033.145629,124.036457,9.233850e+04,4116.696440
min,0.000000,725.000000,132.000000,0.000000,4.051000e+03,514.000000,0.000000,1.283000e+03,0.000000
25%,0.000000,3474.250000,2033.000000,37.000000,1.368875e+04,2884.500000,0.000000,1.206875e+04,666.750000
50%,18.000000,5672.500000,3167.000000,97.000000,2.221950e+04,4454.000000,15.500000,2.212550e+04,1129.000000
75%,77.000000,11495.000000,6084.750000,204.500000,4.548750e+04,8269.750000,77.250000,5.213100e+04,2278.750000
max,1475.000000,304572.000000,174627.000000,2862.000000,1.104590e+06,200310.000000,1596.000000,1.452697e+06,71179.000000

In [46]:
Device_clean = Device_EST_df2.merge(Location_df, how= 'outer', on = 'GEO_ID')
Device_clean

,est_total_households,est_total_households_with_Device,est_total_households_with_Desktop,est_total_households_with_NO,est_total_households_with_Smartphone,est_total_households_with_NO2,est_total_households_with_Portable,est_total_households_with_NO3,est_total_households_with_Other,est_total_households_with_NO4,est_total_households_No_Device,county,state
GEO_ID,,,,,,,,,,,,,
0500000US01003,83501,77443,62729,4403,70185,9358,53266,1100,1184,0,6058,Baldwin County,Alabama
0500000US01015,44264,38768,30768,3054,32921,3865,25422,1164,1225,82,5496,Calhoun County,Alabama
0500000US01043,30323,26269,19117,654,24088,3948,17024,689,447,48,4054,Cullman County,Alabama
0500000US01049,26462,22675,15879,1440,20442,4172,13094,306,250,0,3787,DeKalb County,Alabama
0500000US01051,30155,26120,21528,599,24958,2809,19449,313,717,0,4035,Elmore County,Alabama
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0500000US72113,53450,36068,25939,4203,30774,7922,11988,593,625,0,17382,Ponce Municipio,Puerto Rico
0500000US72127,147267,91339,61138,6683,81283,21953,43668,1191,4211,0,55928,San Juan Municipio,Puerto Rico
0500000US72135,21511,18109,9721,380,17579,7816,5182,39,0,0,3402,Toa Alta Municipio,Puerto Rico
0500000US72137,26085,22944,12758,383,22146,9052,8807,105,158,0,3141,Toa Baja Municipio,Puerto Rico
0500000US72139,23195,19110,12273,581,18130,5473,9619,185,74,0,4085,Trujillo Alto Municipio,Puerto Rico

In [50]:
Subs_clean = Sub_EST_df.merge(Location_df, how= 'outer', on = 'GEO_ID')
Subs_clean

,est_total_households_with_SUB,est_total_households_with_DU,est_total_households_with_Broadband,est_total_households_with_Cellular,est_total_households_with_Cell_NO,est_total_households_with_Cable,est_total_households_with_SAT,est_total_households_without_SUB,county,state
GEO_ID,,,,,,,,,,
0500000US01003,71067,433,70634,65198,16557,48113,10767,12434,Baldwin County,Alabama
0500000US01015,34344,229,34115,27732,6463,24763,4914,9920,Calhoun County,Alabama
0500000US01043,24503,204,24299,21512,7213,14954,3016,5820,Cullman County,Alabama
0500000US01049,20646,0,20646,18541,4939,14450,2077,5816,DeKalb County,Alabama
0500000US01051,24772,41,24731,20312,2983,20463,2201,5383,Elmore County,Alabama
...,...,...,...,...,...,...,...,...,...,...
0500000US72113,36529,191,36338,34157,15015,20228,1470,16921,Ponce Municipio,Puerto Rico
0500000US72127,78990,2387,76603,67616,26303,45948,4493,68277,San Juan Municipio,Puerto Rico
0500000US72135,7870,101,7769,7547,3512,3797,453,13641,Toa Alta Municipio,Puerto Rico
0500000US72137,11513,103,11410,8044,3059,7901,748,14572,Toa Baja Municipio,Puerto Rico
0500000US72139,18113,43,18070,17322,7453,10158,456,5082,Trujillo Alto Municipio,Puerto Rico

In [60]:
Subs_by_Income_clean = Subs_by_Income_df.merge(Location_df, how= 'outer', on = 'GEO_ID')
Subs_by_Income_clean

,est_total_20k_households_with_DU,est_total_20k_households_with_Broadband,est_total_20k_households_without_SUB,est_total_under75k_households_with_DU,est_total_under75k_households_with_BB,est_total_under75k_households_without_SUB,est_total_75k_households_with_DU,est_total_75k_households_with_BB,est_total_75k_households_without_SUB,county,state
GEO_ID,,,,,,,,,,,
0500000US01003,162.0,7149.0,3177.0,271.0,34396.0,7731.0,0.0,29089.0,1526.0,Baldwin County,Alabama
0500000US01015,66.0,6094.0,3886.0,135.0,16402.0,4375.0,28.0,11619.0,1659.0,Calhoun County,Alabama
0500000US01043,0.0,4020.0,1915.0,204.0,12595.0,3085.0,0.0,7684.0,820.0,Cullman County,Alabama
0500000US01049,0.0,3853.0,2934.0,0.0,10649.0,2542.0,0.0,6144.0,340.0,DeKalb County,Alabama
0500000US01051,0.0,2908.0,2174.0,41.0,11261.0,2274.0,0.0,10562.0,935.0,Elmore County,Alabama
...,...,...,...,...,...,...,...,...,...,...,...
0500000US72113,191.0,16894.0,11751.0,0.0,16169.0,4836.0,0.0,3275.0,334.0,Ponce Municipio,Puerto Rico
0500000US72127,432.0,21760.0,45717.0,1533.0,36499.0,21085.0,422.0,18344.0,1475.0,San Juan Municipio,Puerto Rico
0500000US72135,45.0,1904.0,6925.0,56.0,4051.0,6152.0,0.0,1814.0,564.0,Toa Alta Municipio,Puerto Rico
0500000US72137,0.0,2724.0,7575.0,26.0,6804.0,6436.0,77.0,1882.0,561.0,Toa Baja Municipio,Puerto Rico
0500000US72139,0.0,4729.0,3188.0,43.0,9947.0,1824.0,0.0,3394.0,70.0,Trujillo Alto Municipio,Puerto Rico

In [ ]:
Device_clean.to_csv(r"Initial Clean Data/est_device_data_clean.csv", index = False)
Subs_clean.to_csv(r"Initial Clean Data/est_internet_subs_data_clean.csv", index = False)
Subs_by_Income_clean.to_csv(r"Initial Clean Data/est_internet_subs_by_income_data_clean.csv", index = False)

def change_type(value):
    """Assign labels to country and year pairs according to their recorded exports
    """
    if value < 500:
        label = "Less than 500"
    elif value < 5000:
        label = "Between 500 and 5,000"
    elif value < 50000:
        label = "Between 5,000 and 50,000"
    else:
        label = "More than 50,000"
    return label
EST_df.apply(change_type, axis = "index")

In [52]:
Subs_clean.groupby('county')["est_total_households_without_SUB"].mean()

county
Ada County            17743.0
Adams County           9993.0
Aiken County          11639.0
Alachua County        12797.0
Alamance County       13001.0
                       ...
Yellowstone County    10315.0
Yolo County            6939.0
York County           13380.0
Yuba County            6314.0
Yuma County           14742.0
Name: est_total_households_without_SUB, Length: 667, dtype: float64

In [66]:
ax = (
    Device_clean.groupby(["county", "state"])["est_total_households_No_Device"]
    .sum()
    .reset_index(name="state")
    .sort_values(by="est_total_households_No_Device", ascending=False)
    .plot.bar(x="state", y="Households with no Device")
)
plt.figure(figsize = (2,1),dpi =80)
ax.set_xlabel("State")
ax.set_ylabel("Households with no Device")
_ = ax.set_title("Device Level by County")

ValueError: cannot insert state, already exists

In [ ]:
df_pie = (
    cleaned_df.groupby(["GEO_area_name"])["EST_T_T_hhlds"]
    .sum()
    .reset_index(name="Total Households")
    .sort_values(by="Total Households", ascending=False)
)
ax = df_pie.plot.pie(y="Total Households", labels=df_pie.GEO_area_name, autopct="%1.2f%%")
_ = ax.set_title("State Households Pie")

In [ ]:
cal_df = cleaned_df.copy()
cal_df["is_Cal"] = [
    "California" if x == "California" else "Rest of US" for x in cleaned_df["GEO_area_name"]
]


ax_Cal= (
    cal_df.groupby(["is_Cal"])["EST_T_T_hhlds"]
    .sum()
    .reset_index(name="Total Households")
    .plot.pie(y="Total Households", labels=cal_df.is_Cal, autopct="%1.f%%")
)

##Could Maybe Filter out California

In [ ]:
NY_df = cleaned_df.copy()
NY_df["NY"] = [
    "New York" if x == "New York" else "Rest of US" for x in cleaned_df["GEO_area_name"]
]


ax_NY= (
    NY_df.groupby(["is_NY"])["EST_T_T_hhlds"]
    .sum()
    .reset_index(name="Total Households")
    .plot.pie(y="Total Households", labels=NY_df.is_NY, autopct="%1.f%%")
)

In [ ]:
ax2 = cleaned_df.plot.scatter(x="EST_T_T_hhlds", y="EST_T_T_hhlds_type_of_internet_subscriptions_without_an_internet_subscription")
ax2.set_xlabel("Total Households")
ax2.set_ylabel("Households Without Internet")
ax2 = ax2.set_title("Higher Population Means More w/out Internet Subs")

In [ ]:
ax3 = cleaned_df.plot.scatter(x="EST_T_T_hhlds_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_less_than_$20,000:", y="EST_T_T_hhlds_type_of_internet_subscriptions_without_an_internet_subscription")
ax3.set_xlabel("Number of 20k households")
ax3.set_ylabel("Households Without Internet")
ax3 = ax3.set_title("Less Income Less Internet Subs")

In [ ]:
ax4 = cleaned_df.plot.scatter(x="EST_T_T_hhlds_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more:", y="EST_T_T_hhlds_type_of_internet_subscriptions_without_an_internet_subscription")
ax4.set_xlabel("Number of 75k Households")
ax4.set_ylabel("Total Households Without Internet")
ax4 = ax4.set_title("More Income May Lead to More w/out Internet Subs in Certain Areas")

In [ ]:
ax5 = cleaned_df.plot.scatter(x="EST_T_T_hhlds_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more:", y="EST_T_T_hhlds_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more_without_an_internet_subscription")
ax5.set_xlabel("Number of 75k Households")
ax5.set_ylabel("Number of 75k Households Without Internet")
ax5 = ax5.set_title("75k income Without Internet Subs")
## Increase Prob Due to Higher Population

In [ ]:
ax6 = cleaned_df.plot.scatter(x="EST_T_T_hhlds", y="EST_T_T_hhlds_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more_without_an_internet_subscription")
ax6.set_xlabel("Total Households")
ax6.set_ylabel("75k Households Without Internet")
ax6 = ax6.set_title("Higher Population Means More 75k w/out Internet Subs")
##Would Have to start to look at state/ county level

In [ ]:
US_T = ['California', 'New York', 'Puerto Rico', 'Virginia', 'Georgia']
df_US_T = cleaned_df
df_US_T["GEO_area_name"] = cleaned_df["GEO_area_name"].isin(US_T).drop(["GEO_area_name"], axis=0).T.reset_index()
df_US_T

In [ ]:
US_T = ["California", "New York", "Puerto Rico", "Virginia", "Georgia"]
df_US_T = cleaned_df[cleaned_df["GEO_are_name"].isin(US_T)].drop(["GEO_area_name"], axis=1)reset_index()

colors = {
    "California": "green",
    "New York": "orange",
    "Puerto Rico": "red",
    "Virginia": "purple",
    "Georgia": "blue",
}

_, ax7 = plt.subplots()
for key, group in cleaned_df.groupby("GEO_area_name"):
    group.plot.scatter(ax7=ax7, x="EST_T_T_hhlds", y="EST_T_T_hhlds_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more_without_an_internet_subscription", label=key, color=colors[key])

ax7.set_xlabel("Total Households")
ax7.set_ylabel("75k Households wOUT Internet Subs")
_ = ax.set_title(
    "Africa's countries are almost all low GDP compared to Europe and America"
)

data = [df1["A"], df2["A"]]

headers = ["df1", "df2"]

df3 = pd.concat(data, axis=1, keys=headers)

my_list*(chips.shape[0]/len(my_list))
chips["id"].unique()