In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/Users/jjruiz/Downloads/Internet_Subs_by_State.csv')
df2 = pd.read_csv('/Users/jjruiz/Downloads/Internet_Subs_by_State.csv', index_col = 0)

In [3]:
df.head()

,GEO_ID,NAME,S2801_C01_001E,S2801_C01_001M,S2801_C01_002E,S2801_C01_002M,S2801_C01_003E,S2801_C01_003M,S2801_C01_004E,S2801_C01_004M,...,S2801_C02_027E,S2801_C02_027M,S2801_C02_028E,S2801_C02_028M,S2801_C02_029E,S2801_C02_029M,S2801_C02_030E,S2801_C02_030M,S2801_C02_031E,S2801_C02_031M
0,id,Geographic Area Name,Estimate!!Total!!Total households,Margin of Error!!Total!!Total households,Estimate!!Total!!Total households!!TYPES OF CO...,Margin of Error!!Total!!Total households!!TYPE...,Estimate!!Total!!Total households!!TYPES OF CO...,Margin of Error!!Total!!Total households!!TYPE...,Estimate!!Total!!Total households!!TYPES OF CO...,Margin of Error!!Total!!Total households!!TYPE...,...,Estimate!!Percent!!Total households!!HOUSEHOLD...,Margin of Error!!Percent!!Total households!!HO...,Estimate!!Percent!!Total households!!HOUSEHOLD...,Margin of Error!!Percent!!Total households!!HO...,Estimate!!Percent!!Total households!!HOUSEHOLD...,Margin of Error!!Percent!!Total households!!HO...,Estimate!!Percent!!Total households!!HOUSEHOLD...,Margin of Error!!Percent!!Total households!!HO...,Estimate!!Percent!!Total households!!HOUSEHOLD...,Margin of Error!!Percent!!Total households!!HO...
1,0400000US01,Alabama,1897576,10370,1696826,11925,1297938,14225,66791,4017,...,18.3,0.7,(X),(X),0.2,0.1,94.3,0.6,5.5,0.6
2,0400000US02,Alaska,252199,3658,240277,3657,198527,4332,7642,1181,...,14.2,1.6,(X),(X),0.2,0.2,94.9,1.0,4.9,1.0
3,0400000US04,Arizona,2670441,12014,2526296,12774,2126119,14921,98511,4408,...,14.6,0.6,(X),(X),0.1,0.1,95.9,0.3,4.0,0.3
4,0400000US05,Arkansas,1163647,8530,1040974,9157,773212,11160,45043,2893,...,19.6,0.8,(X),(X),0.1,0.1,92.6,0.8,7.3,0.8

In [5]:
df.shape

(53, 126)

df2.columns = df2.iloc[0]
df2 = df2.iloc[1:].reset_index(drop=False)
df2["GEO_ID"] = df2["GEO_ID"].astype(str)
df2["GEO_ID"] = df2["GEO_ID"].str[7:11]
df2 = df2.set_index('GEO_ID')
df2.head()

In [69]:
df.columns = df.iloc[0]
df = df.iloc[1:].reset_index(drop=True)
df.head()

,id,Geographic Area Name,Estimate!!Total!!Total households,Margin of Error!!Total!!Total households,Estimate!!Total!!Total households!!TYPES OF COMPUTER!!Has one or more types of computing devices:,Margin of Error!!Total!!Total households!!TYPES OF COMPUTER!!Has one or more types of computing devices:,Estimate!!Total!!Total households!!TYPES OF COMPUTER!!Has one or more types of computing devices:!!Desktop or laptop,Margin of Error!!Total!!Total households!!TYPES OF COMPUTER!!Has one or more types of computing devices:!!Desktop or laptop,Estimate!!Total!!Total households!!TYPES OF COMPUTER!!Has one or more types of computing devices:!!Desktop or laptop!!Desktop or laptop with no other type of computing device,Margin of Error!!Total!!Total households!!TYPES OF COMPUTER!!Has one or more types of computing devices:!!Desktop or laptop!!Desktop or laptop with no other type of computing device,...,"Estimate!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$20,000 to $74,999:!!Without an Internet subscription","Margin of Error!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$20,000 to $74,999:!!Without an Internet subscription","Estimate!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:","Margin of Error!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:","Estimate!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:!!With dial-up Internet subscription alone","Margin of Error!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:!!With dial-up Internet subscription alone","Estimate!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:!!With a broadband Internet subscription","Margin of Error!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:!!With a broadband Internet subscription","Estimate!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:!!Without an Internet subscription","Margin of Error!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:!!Without an Internet subscription"
0,0400000US01,Alabama,1897576,10370,1696826,11925,1297938,14225,66791,4017,...,18.3,0.7,(X),(X),0.2,0.1,94.3,0.6,5.5,0.6
1,0400000US02,Alaska,252199,3658,240277,3657,198527,4332,7642,1181,...,14.2,1.6,(X),(X),0.2,0.2,94.9,1.0,4.9,1.0
2,0400000US04,Arizona,2670441,12014,2526296,12774,2126119,14921,98511,4408,...,14.6,0.6,(X),(X),0.1,0.1,95.9,0.3,4.0,0.3
3,0400000US05,Arkansas,1163647,8530,1040974,9157,773212,11160,45043,2893,...,19.6,0.8,(X),(X),0.1,0.1,92.6,0.8,7.3,0.8
4,0400000US06,California,13157873,23844,12513521,25055,10766546,30830,364395,10538,...,13.3,0.3,(X),(X),0.1,0.1,96.4,0.1,3.5,0.1

In [71]:
df["id"] = df["id"].astype(str)
df["id"] = df["id"].str[7:11]
df.head()

,id,Geographic Area Name,Estimate!!Total!!Total households,Margin of Error!!Total!!Total households,Estimate!!Total!!Total households!!TYPES OF COMPUTER!!Has one or more types of computing devices:,Margin of Error!!Total!!Total households!!TYPES OF COMPUTER!!Has one or more types of computing devices:,Estimate!!Total!!Total households!!TYPES OF COMPUTER!!Has one or more types of computing devices:!!Desktop or laptop,Margin of Error!!Total!!Total households!!TYPES OF COMPUTER!!Has one or more types of computing devices:!!Desktop or laptop,Estimate!!Total!!Total households!!TYPES OF COMPUTER!!Has one or more types of computing devices:!!Desktop or laptop!!Desktop or laptop with no other type of computing device,Margin of Error!!Total!!Total households!!TYPES OF COMPUTER!!Has one or more types of computing devices:!!Desktop or laptop!!Desktop or laptop with no other type of computing device,...,"Estimate!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$20,000 to $74,999:!!Without an Internet subscription","Margin of Error!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$20,000 to $74,999:!!Without an Internet subscription","Estimate!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:","Margin of Error!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:","Estimate!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:!!With dial-up Internet subscription alone","Margin of Error!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:!!With dial-up Internet subscription alone","Estimate!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:!!With a broadband Internet subscription","Margin of Error!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:!!With a broadband Internet subscription","Estimate!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:!!Without an Internet subscription","Margin of Error!!Percent!!Total households!!HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2019 INFLATION-ADJUSTED DOLLARS)!!$75,000 or more:!!Without an Internet subscription"
0,US01,Alabama,1897576,10370,1696826,11925,1297938,14225,66791,4017,...,18.3,0.7,(X),(X),0.2,0.1,94.3,0.6,5.5,0.6
1,US02,Alaska,252199,3658,240277,3657,198527,4332,7642,1181,...,14.2,1.6,(X),(X),0.2,0.2,94.9,1.0,4.9,1.0
2,US04,Arizona,2670441,12014,2526296,12774,2126119,14921,98511,4408,...,14.6,0.6,(X),(X),0.1,0.1,95.9,0.3,4.0,0.3
3,US05,Arkansas,1163647,8530,1040974,9157,773212,11160,45043,2893,...,19.6,0.8,(X),(X),0.1,0.1,92.6,0.8,7.3,0.8
4,US06,California,13157873,23844,12513521,25055,10766546,30830,364395,10538,...,13.3,0.3,(X),(X),0.1,0.1,96.4,0.1,3.5,0.1

In [80]:
df.columns = df.columns.str.lower().str.replace('!!', '_').str.replace(' ', '_').str.replace('-', '_').str.replace(':_', '_')

In [81]:
df.head()

,id,geographic_area_name,estimate_total_total_households,margin_of_error_total_total_households,estimate_total_total_households_types_of_computer_has_one_or_more_types_of_computing_devices:,margin_of_error_total_total_households_types_of_computer_has_one_or_more_types_of_computing_devices:,estimate_total_total_households_types_of_computer_has_one_or_more_types_of_computing_devices_desktop_or_laptop,margin_of_error_total_total_households_types_of_computer_has_one_or_more_types_of_computing_devices_desktop_or_laptop,estimate_total_total_households_types_of_computer_has_one_or_more_types_of_computing_devices_desktop_or_laptop_desktop_or_laptop_with_no_other_type_of_computing_device,margin_of_error_total_total_households_types_of_computer_has_one_or_more_types_of_computing_devices_desktop_or_laptop_desktop_or_laptop_with_no_other_type_of_computing_device,...,"estimate_percent_total_households_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$20,000_to_$74,999_without_an_internet_subscription","margin_of_error_percent_total_households_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$20,000_to_$74,999_without_an_internet_subscription","estimate_percent_total_households_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more:","margin_of_error_percent_total_households_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more:","estimate_percent_total_households_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more_with_dial_up_internet_subscription_alone","margin_of_error_percent_total_households_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more_with_dial_up_internet_subscription_alone","estimate_percent_total_households_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more_with_a_broadband_internet_subscription","margin_of_error_percent_total_households_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more_with_a_broadband_internet_subscription","estimate_percent_total_households_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more_without_an_internet_subscription","margin_of_error_percent_total_households_household_income_in_the_past_12_months_(in_2019_inflation_adjusted_dollars)_$75,000_or_more_without_an_internet_subscription"
0,US01,Alabama,1897576,10370,1696826,11925,1297938,14225,66791,4017,...,18.3,0.7,(X),(X),0.2,0.1,94.3,0.6,5.5,0.6
1,US02,Alaska,252199,3658,240277,3657,198527,4332,7642,1181,...,14.2,1.6,(X),(X),0.2,0.2,94.9,1.0,4.9,1.0
2,US04,Arizona,2670441,12014,2526296,12774,2126119,14921,98511,4408,...,14.6,0.6,(X),(X),0.1,0.1,95.9,0.3,4.0,0.3
3,US05,Arkansas,1163647,8530,1040974,9157,773212,11160,45043,2893,...,19.6,0.8,(X),(X),0.1,0.1,92.6,0.8,7.3,0.8
4,US06,California,13157873,23844,12513521,25055,10766546,30830,364395,10538,...,13.3,0.3,(X),(X),0.1,0.1,96.4,0.1,3.5,0.1

In [82]:
df.shape

(52, 126)

In [86]:
rename_dict_short = {
    "id", "geographic_area_name", "estimate_total_households","margin_of_error_total_total_households",
    "Bucket_1", "ME_Bucket_1","Bucket_2", "ME_Bucket_2","Bucket_3", "ME_Bucket_3","Bucket_4", "ME_Bucket_4",
    "Bucket_5", "ME_Bucket_5","Bucket_6", "ME_Bucket_6","Bucket_7", "ME_Bucket_7","Bucket_8", "ME_Bucket_8",
    "Bucket_9", "ME_Bucket_9","Bucket_10", "ME_Bucket_10","Bucket_11", "ME_Bucket_11","Bucket_12", "ME_Bucket_12",
    "Bucket_13", "ME_Bucket_13","Bucket_14", "ME_Bucket_14","Bucket_15", "ME_Bucket_15","Bucket_16", "ME_Bucket_16",
    "Bucket_17", "ME_Bucket_17","Bucket_18", "ME_Bucket_18","Bucket_19", "ME_Bucket_19","Bucket_20", "ME_Bucket_20",
    "Bucket_21", "ME_Bucket_21","Bucket_22", "ME_Bucket_22","Bucket_23", "ME_Bucket_23","Bucket_24", "ME_Bucket_24",
    "Bucket_25", "ME_Bucket_25","Bucket_26", "ME_Bucket_26","Bucket_27", "ME_Bucket_27","Bucket_28", "ME_Bucket_28",
    "Bucket_29", "ME_Bucket_29","Bucket_30", "ME_Bucket_30",
    "Bucket_31", "ME_Bucket_31","Bucket_32", "ME_Bucket_32",
    "Bucket_33", "ME_Bucket_33","Bucket_34", "ME_Bucket_34",
    "Bucket_35", "ME_Bucket_35","Bucket_36", "ME_Bucket_36","Bucket_37","ME_Bucket_37","Bucket_38", "ME_Bucket_38",
    "Bucket_39", "ME_Bucket_39","Bucket_40", "ME_Bucket_40","Bucket_41","ME_Bucket_41","Bucket_42", "ME_Bucket_42",
    "Bucket_43", "ME_Bucket_43","Bucket_44", "ME_Bucket_44","Bucket_45","ME_Bucket_45","Bucket_46", "ME_Bucket_46",
    "Bucket_47", "ME_Bucket_47","Bucket_48", "ME_Bucket_48","Bucket_49", "ME_Bucket_49","Bucket_50", "ME_Bucket_50",
    "Bucket_51", "ME_Bucket_51","Bucket_52", "ME_Bucket_52","Bucket_53", "ME_Bucket_53","Bucket_54", "ME_Bucket_54",
    "Bucket_55", "ME_Bucket_55","Bucket_56", "ME_Bucket_56","Bucket_57", "ME_Bucket_57","Bucket_58", "ME_Bucket_58",
    "Bucket_59", "ME_Bucket_59","Bucket_60", "ME_Bucket_60",
}

In [90]:
df.set_axis([
    "id", "geographic_area_name", "estimate_total_households","margin_of_error_total_total_households",
    "Bucket_1", "ME_Bucket_1","Bucket_2", "ME_Bucket_2","Bucket_3", "ME_Bucket_3","Bucket_4", "ME_Bucket_4",
    "Bucket_5", "ME_Bucket_5","Bucket_6", "ME_Bucket_6","Bucket_7", "ME_Bucket_7","Bucket_8", "ME_Bucket_8",
    "Bucket_9", "ME_Bucket_9","Bucket_10", "ME_Bucket_10","Bucket_11", "ME_Bucket_11","Bucket_12", "ME_Bucket_12",
    "Bucket_13", "ME_Bucket_13","Bucket_14", "ME_Bucket_14","Bucket_15", "ME_Bucket_15","Bucket_16", "ME_Bucket_16",
    "Bucket_17", "ME_Bucket_17","Bucket_18", "ME_Bucket_18","Bucket_19", "ME_Bucket_19","Bucket_20", "ME_Bucket_20",
    "Bucket_21", "ME_Bucket_21","Bucket_22", "ME_Bucket_22","Bucket_23", "ME_Bucket_23","Bucket_24", "ME_Bucket_24",
    "Bucket_25", "ME_Bucket_25","Bucket_26", "ME_Bucket_26","Bucket_27", "ME_Bucket_27","Bucket_28", "ME_Bucket_28",
    "Bucket_29", "ME_Bucket_29","Bucket_30", "ME_Bucket_30",
    "Bucket_31", "ME_Bucket_31","Bucket_32", "ME_Bucket_32",
    "Bucket_33", "ME_Bucket_33","Bucket_34", "ME_Bucket_34",
    "Bucket_35", "ME_Bucket_35","Bucket_36", "ME_Bucket_36","Bucket_37","ME_Bucket_37","Bucket_38", "ME_Bucket_38",
    "Bucket_39", "ME_Bucket_39","Bucket_40", "ME_Bucket_40","Bucket_41","ME_Bucket_41","Bucket_42", "ME_Bucket_42",
    "Bucket_43", "ME_Bucket_43","Bucket_44", "ME_Bucket_44","Bucket_45","ME_Bucket_45","Bucket_46", "ME_Bucket_46",
    "Bucket_47", "ME_Bucket_47","Bucket_48", "ME_Bucket_48","Bucket_49", "ME_Bucket_49","Bucket_50", "ME_Bucket_50",
    "Bucket_51", "ME_Bucket_51","Bucket_52", "ME_Bucket_52","Bucket_53", "ME_Bucket_53","Bucket_54", "ME_Bucket_54",
    "Bucket_55", "ME_Bucket_55","Bucket_56", "ME_Bucket_56","Bucket_57", "ME_Bucket_57","Bucket_58", "ME_Bucket_58",
    "Bucket_59", "ME_Bucket_59","Bucket_60", "ME_Bucket_60","Bucket_61", "ME_Bucket_61"
], axis='columns', inplace =True)
df.head()

,id,geographic_area_name,estimate_total_households,margin_of_error_total_total_households,Bucket_1,ME_Bucket_1,Bucket_2,ME_Bucket_2,Bucket_3,ME_Bucket_3,...,Bucket_57,ME_Bucket_57,Bucket_58,ME_Bucket_58,Bucket_59,ME_Bucket_59,Bucket_60,ME_Bucket_60,Bucket_61,ME_Bucket_61
0,US01,Alabama,1897576,10370,1696826,11925,1297938,14225,66791,4017,...,18.3,0.7,(X),(X),0.2,0.1,94.3,0.6,5.5,0.6
1,US02,Alaska,252199,3658,240277,3657,198527,4332,7642,1181,...,14.2,1.6,(X),(X),0.2,0.2,94.9,1.0,4.9,1.0
2,US04,Arizona,2670441,12014,2526296,12774,2126119,14921,98511,4408,...,14.6,0.6,(X),(X),0.1,0.1,95.9,0.3,4.0,0.3
3,US05,Arkansas,1163647,8530,1040974,9157,773212,11160,45043,2893,...,19.6,0.8,(X),(X),0.1,0.1,92.6,0.8,7.3,0.8
4,US06,California,13157873,23844,12513521,25055,10766546,30830,364395,10538,...,13.3,0.3,(X),(X),0.1,0.1,96.4,0.1,3.5,0.1

In [91]:
df = df.set_index('id')
df.head()

,geographic_area_name,estimate_total_households,margin_of_error_total_total_households,Bucket_1,ME_Bucket_1,Bucket_2,ME_Bucket_2,Bucket_3,ME_Bucket_3,Bucket_4,...,Bucket_57,ME_Bucket_57,Bucket_58,ME_Bucket_58,Bucket_59,ME_Bucket_59,Bucket_60,ME_Bucket_60,Bucket_61,ME_Bucket_61
id,,,,,,,,,,,,,,,,,,,,,
US01,Alabama,1897576,10370,1696826,11925,1297938,14225,66791,4017,1579910,...,18.3,0.7,(X),(X),0.2,0.1,94.3,0.6,5.5,0.6
US02,Alaska,252199,3658,240277,3657,198527,4332,7642,1181,228924,...,14.2,1.6,(X),(X),0.2,0.2,94.9,1.0,4.9,1.0
US04,Arizona,2670441,12014,2526296,12774,2126119,14921,98511,4408,2362834,...,14.6,0.6,(X),(X),0.1,0.1,95.9,0.3,4.0,0.3
US05,Arkansas,1163647,8530,1040974,9157,773212,11160,45043,2893,964110,...,19.6,0.8,(X),(X),0.1,0.1,92.6,0.8,7.3,0.8
US06,California,13157873,23844,12513521,25055,10766546,30830,364395,10538,11905686,...,13.3,0.3,(X),(X),0.1,0.1,96.4,0.1,3.5,0.1

In [101]:
ME_df = df.filter([
    "ME_Bucket_1", "ME_Bucket_2","ME_Bucket_3","ME_Bucket_4",
     "ME_Bucket_5", "ME_Bucket_6","ME_Bucket_7", "ME_Bucket_8",
     "ME_Bucket_9","ME_Bucket_10","ME_Bucket_11", "ME_Bucket_12",
     "ME_Bucket_13","ME_Bucket_14", "ME_Bucket_15", "ME_Bucket_16",
     "ME_Bucket_17", "ME_Bucket_18", "ME_Bucket_19", "ME_Bucket_20",
     "ME_Bucket_21", "ME_Bucket_22", "ME_Bucket_23","ME_Bucket_24",
     "ME_Bucket_25", "ME_Bucket_26", "ME_Bucket_27", "ME_Bucket_28",
     "ME_Bucket_29","ME_Bucket_30","ME_Bucket_31", "ME_Bucket_32",
    "ME_Bucket_33", "ME_Bucket_34","ME_Bucket_35","ME_Bucket_36",
    "ME_Bucket_37","ME_Bucket_38","ME_Bucket_39","ME_Bucket_40",
    "ME_Bucket_41","ME_Bucket_42","ME_Bucket_43", "ME_Bucket_44",
    "ME_Bucket_45","ME_Bucket_46","ME_Bucket_47", "ME_Bucket_48", "ME_Bucket_49","ME_Bucket_50",
    "ME_Bucket_51", "ME_Bucket_52", "ME_Bucket_53","ME_Bucket_54","ME_Bucket_55","ME_Bucket_56", 
    "ME_Bucket_57","ME_Bucket_58","ME_Bucket_59","ME_Bucket_60","ME_Bucket_61"
], axis=1)
ME_df.head()

In [102]:
ME_df.head()

,ME_Bucket_1,ME_Bucket_2,ME_Bucket_3,ME_Bucket_4,ME_Bucket_5,ME_Bucket_6,ME_Bucket_7,ME_Bucket_8,ME_Bucket_9,ME_Bucket_10,...,ME_Bucket_52,ME_Bucket_53,ME_Bucket_54,ME_Bucket_55,ME_Bucket_56,ME_Bucket_57,ME_Bucket_58,ME_Bucket_59,ME_Bucket_60,ME_Bucket_61
id,,,,,,,,,,,,,,,,,,,,,
US01,11925,14225,4017,13069,7972,13684,2350,3536,450,7264,...,1.4,1.4,(X),0.1,0.7,0.7,(X),0.1,0.6,0.6
US02,3657,4332,1181,3887,2705,4283,404,1921,163,1252,...,4.4,4.4,(X),0.2,1.6,1.6,(X),0.2,1.0,1.0
US04,12774,14921,4408,14105,9790,17680,2661,4463,235,6021,...,1.3,1.3,(X),0.1,0.6,0.6,(X),0.1,0.3,0.3
US05,9157,11160,2893,9395,7998,11192,1523,2004,143,5336,...,1.7,1.7,(X),0.1,0.8,0.8,(X),0.1,0.8,0.8
US06,25055,30830,10538,28254,20002,35533,4238,11641,562,11937,...,0.5,0.5,(X),0.1,0.3,0.3,(X),0.1,0.1,0.1

for column in df:
    print(df[column])

In [ ]:
data = [df1["A"], df2["A"]]

headers = ["df1", "df2"]

df3 = pd.concat(data, axis=1, keys=headers)